version: "3"
services:
  jenkins:
    build: dockerfile/jenkins
    image: registry.cn-qingdao.aliyuncs.com/wangdali/codeforfun-jenkins
    container_name: jenkins
    user: root
    environment:
      TZ: Asia/Shanghai
    volumes:
      - "./data/jenkins:/var/jenkins_home"
      - "./ubuntu.pem:/ubuntu.pem"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "${DOCKER_PATH}:/usr/bin/docker"
      - "${DOCKER_COMPOSE_PATH}:/usr/bin/docker-compose"
    networks:
      - codeforfun-net
  webhooks:
    image: registry.cn-qingdao.aliyuncs.com/wangdali/codeforfun-webhooks
    container_name: webhooks
    environment:
      TZ: Asia/Shanghai
    networks:
      - codeforfun-net
  redmine:
    image: redmine:3.4
    container_name: redmine
    volumes:
      - "./data/redmine:/usr/src/redmine/files"
    environment:
      REDMINE_DB_MYSQL: mysql
      REDMINE_DB_PASSWORD: root
      TZ: Asia/Shanghai
    networks:
      - codeforfun-net
networks:
  codeforfun-net:
    external:
      name: codeforfun-network