version: "3"
services:
  nginx:
    image: nginx:1.15.0
    container_name: nginx
    ports:
      - 80:80
    environment:
      TZ: Asia/Shanghai
    volumes:
      - "./conf/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./conf/nginx/conf.d:/etc/nginx/conf.d"
    networks:
      - codeforfun-net
networks:
  codeforfun-net:
    external:
      name: codeforfun-network