version: "3"
services:
  jenkins:
    build: dockerfile/jenkins
    image: registry.cn-qingdao.aliyuncs.com/wangdali/codeforfun-jenkins
    container_name: jenkins
    environment:
      TZ: Asia/Shanghai
    user: root
    volumes:
      - "./data/jenkins:/var/jenkins_home"
      - "./ubuntu.pem:/ubuntu.pem"
    networks:
      - codeforfun-net
networks:
  codeforfun-net:
    external:
      name: codeforfun-network