version: "3"
services:
  nginx:
    image: nginx:1.15.0
    container_name: nginx
    ports:
      - 80:80
    environment:
      TZ: Asia/Shanghai
    volumes:
      - "./conf/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./conf/nginx/conf.d:/etc/nginx/conf.d"
    networks:
      - codeforfun-net
  front-pc:
    image: registry.cn-qingdao.aliyuncs.com/wangdali/codeforfun-front-pc
    container_name: front-pc
    environment:
      TZ: Asia/Shanghai
    networks:
      - codeforfun-net
  mysql:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - "./data/mysql:/var/lib/mysql"
      - "./conf/mysql:/etc/mysql/conf.d"
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Shanghai
    networks:
      - codeforfun-net
networks:
  codeforfun-net:
    external:
      name: codeforfun-network